# Generated by Django 4.2.11 on 2025-04-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationlog',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
