# Generated by Django 4.2.11 on 2025-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_conversationlog_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationreminder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='medicationreminder',
            name='time',
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='appropriate',
            field=models.CharField(choices=[('Before Food', 'Before Food'), ('After Food', 'After Food')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='duration',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='frequency',
            field=models.CharField(max_length=50),
        ),
    ]
