# Generated by Django 4.2.11 on 2025-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elderlyprofile',
            name='preferred_language',
            field=models.CharField(default='ne', max_length=10),
        ),
    ]
